baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'HappyMod'

[params]
  description = "A showcase of mobile applications"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Apps"
    url = "/app/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Add the module configuration from config.toml
[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
