backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "app" # Used in routes, e.g., /admin/collections/app
    label: "App" # Used in the UI
    folder: "content/app" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "App Name", name: "appName", widget: "string"}
      - {label: "App Logo", name: "appLogo", widget: "image", required: false}
      - {label: "Download On Click", name: "downloadOnClick", widget: "string", required: false}
      - {label: "App Version", name: "appVersion", widget: "string", required: false}
      - {label: "Mod Information", name: "modInfo", widget: "markdown", required: false}
      - {label: "Screenshots", name: "screenshots", widget: "list", field: {label: "Image", name: "image", widget: "image"}, required: false}
      - {label: "Body", name: "body", widget: "markdown"}